openapi: 3.0.1
info:
  title: MasMovil Ticketing API - Inbound (External Systems > MasMovil)
  description: This is the ticketing-api server. Another ticker
  contact:
    email: ticketing_squad@masmovil.com
  version: 1.1.8
servers:
- url: '{protocol}://{environment}'
  variables:
    protocol:
      default: https
      enum:
      - https
      - http
    environment:
      default: ticketing.dev.k8s.masmovil.com/v1/api
      enum:
      - 0.0.0.0:8080
      - ticketing.dev.k8s.masmovil.com/v1/api
      - ticketing.private.sta.k8s.masmovil.com/v1/api
tags:
- name: Ticket
  description: Operations about Tickets
paths:
  /ticket:
    post:
      tags:
      - Ticket
      summary: Create new ticket
      description: Creates a ticket in MasMovil ticketing tool.
      operationId: createTicket
      parameters:
      - name: x-api-key
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Fields needed to create a ticket in MasMovil Ticketing tool
        content:
          application/json:
            schema:
              type: object
            examples:
              NetworkIncident:
                $ref: '#/components/examples/NetworkIncident'
              FTTHFault:
                $ref: '#/components/examples/FTTHFault'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
      security:
      - bearerAuth: []
  /ticket/{ticketId}:
    get:
      tags:
      - Ticket
      summary: Get a ticket by id
      description: Retrieves the details of a ticket that has previously been created.
      operationId: getTicketById
      parameters:
      - name: ticketId
        in: path
        description: The Ticket ID in MasMovil ticketing tool. You can use either
          ID or KEY.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: expand
        in: query
        description: Filter for ticket response body. (You must add 'attachment' query
          param to get ticket attachments in response body)
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
            enum:
            - attachment
      - name: x-api-key
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Ticket response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
      security:
      - bearerAuth: []
    patch:
      tags:
      - Ticket
      summary: Update an existing ticket
      description: |
        This service can be used to update ticket information.

        For udating ticket status, you must provide a transtition ID to apply. You can get this ID through this *GET* request: **/ticket/{ticketId}/transitions**

        If your system needs to use a callback to send back information about previous MasMovil request, you must use this service using especified integration fields.
      operationId: updateTicket
      parameters:
      - name: ticketId
        in: path
        description: The Ticket ID in MasMovil ticketing tool. You can use either
          ID or KEY.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: x-api-key
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: |
          Body must include the ticket fields that need to be updated.
          See examples below.
        content:
          application/json:
            schema:
              type: object
            examples:
              UpdateStatus:
                $ref: '#/components/examples/UpdateStatus'
              UpdatePriority:
                $ref: '#/components/examples/UpdatePriority'
              UpdateGroup:
                $ref: '#/components/examples/UpdateGroup'
        required: true
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
      security:
      - bearerAuth: []
  /ticket/{ticketId}/attachment:
    post:
      tags:
      - Ticket
      summary: Add attachment to ticket
      operationId: addAttachment
      parameters:
      - name: ticketId
        in: path
        description: The Ticket ID in MasMovil ticketing tool. You can use either
          ID or KEY.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: x-api-key
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: |
          Both fields name and data are required.
          Data must be base64 encoded.
        content:
          application/json:
            schema:
              type: object
            examples:
              Attachment:
                $ref: '#/components/examples/Attachment'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201_1'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
      security:
      - bearerAuth: []
  /ticket/{ticketId}/comment:
    post:
      tags:
      - Ticket
      summary: Add comment to ticket
      operationId: addComment
      parameters:
      - name: ticketId
        in: path
        description: The Ticket ID in MasMovil ticketing tool. You can use either
          ID or KEY.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: x-api-key
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Property body is mandatory.
        content:
          application/json:
            schema:
              type: object
            examples:
              Comment:
                $ref: '#/components/examples/Comment'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201_2'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
      security:
      - bearerAuth: []
  /ticket/{ticketId}/attachmentWithComment:
    post:
      tags:
      - Ticket
      summary: Add attachment with comment to ticket
      parameters:
      - name: ticketId
        in: path
        description: The Ticket ID in MasMovil ticketing tool. You can use either
          ID or KEY.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: x-api-key
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Both comment and attachment are mandatory.
        content:
          application/json:
            schema:
              type: object
            example:
              comment:
                body: Comment example [^attachment.txt]
              attachment:
                name: attachment.txt
                data: R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs=
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201_3'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
      security:
      - bearerAuth: []
  /ticket/field/{fieldName}:
    get:
      tags:
      - Ticket
      summary: Get information about an API field. It returns info about MasMovil
        ticketing tool field name and allowed values.
      operationId: getFieldInformation
      parameters:
      - name: fieldName
        in: path
        description: The field name in MasMovil ticketing API.
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: customerSegment
      - name: projectKey
        in: query
        description: The project key in MasMovil ticketing tool
        required: true
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
            enum:
            - MAS
      - name: x-api-key
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Get field information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FieldResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
      security:
      - bearerAuth: []
  /ticket/{ticketId}/transitions:
    get:
      tags:
      - Ticket
      summary: Get information about allowed transitions for a ticket.
      operationId: getAllowedTransitions
      parameters:
      - name: ticketId
        in: path
        description: The Ticket ID in MasMovil ticketing tool. You can use either
          ID or KEY.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: x-api-key
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Get transitions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransitionsResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
      security:
      - bearerAuth: []
  /creationDataInfo:
    get:
      tags:
      - Ticket
      summary: Get information about fields needed to create a given type of ticket
      operationId: getFieldsForTicketType
      parameters:
      - name: projectKey
        in: query
        description: The project key in MasMovil ticketing tool
        required: true
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
            enum:
            - MAS
      - name: ticketType
        in: query
        description: The ticket type in MasMovil ticketing tool
        required: true
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
            enum:
            - Avería (FTTH)
            - Avería Cliente
            - Incidencia
            - Reclamación Instalación
            - Cancelación Cliente
      - name: x-api-key
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Fields for ticket type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreationDataInfo'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
      security:
      - bearerAuth: []
  /project/ticketTypes:
    get:
      tags:
      - Ticket
      summary: Get information about ticket types per project
      operationId: getTicketTypes
      parameters:
      - name: x-api-key
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Get ticket types
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketTypesResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
      security:
      - bearerAuth: []
  /ticket/{ticketId}/editableFields:
    get:
      tags:
      - Ticket
      summary: Get information about editable fields for a ticket
      operationId: getEditableFields
      parameters:
      - name: ticketId
        in: path
        description: The Ticket ID in MasMovil ticketing tool. You can use either
          ID or KEY.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Editable Fields for ticket
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditableFields'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
      security:
      - bearerAuth: []
  /search:
    post:
      tags:
      - Ticket
      summary: Search tickets
      description: |
        You can add fields to filter tickets. Allowed special opeators are $like:value and $in:[array], maxResults default results is 10.
        Fields to return must be specified in "fields" json property.
        Field names used in filters can be both Jira field name or ms-ticketing-API name, i.e.: you can use "customerDocument" or "Documento Cliente".
      operationId: searchTickets
      parameters:
      - name: x-api-key
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Filters to apply to search query
        content:
          application/json:
            schema:
              type: object
            examples:
              SearchExample:
                $ref: '#/components/examples/SearchExample'
        required: true
      responses:
        "200":
          description: Ticket response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TicketResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
      security:
      - bearerAuth: []
components:
  schemas:
    TicketResponse:
      type: object
      properties:
        id:
          type: string
          example: "3240786"
        status:
          type: string
          example: EN CURSO
        summary:
          type: string
          example: ERI_MM_OLTZ3562010LAP012_para que se revise
        description:
          type: string
          example: ERI_MM_OLTZ3562010LAP012_para que se revise
        priority:
          type: string
          example: Medium
        ticketType:
          type: string
          example: Incidencia Red
        project:
          type: string
          example: IDR
        createdDate:
          type: string
          example: 2018-02-28T17:43:38.000+0100
        attachment:
          $ref: '#/components/schemas/TicketResponse_attachment'
    FieldResponse:
      type: object
      properties:
        required:
          type: boolean
          example: true
        name:
          type: string
          example: Titulo de la incidencia
    CreationDataInfo:
      type: object
      properties:
        subscriptionNumber:
          $ref: '#/components/schemas/CreationDataInfo_subscriptionNumber'
        icc:
          $ref: '#/components/schemas/CreationDataInfo_icc'
        contactEmail:
          $ref: '#/components/schemas/CreationDataInfo_contactEmail'
    EditableFields:
      type: object
      properties:
        description:
          $ref: '#/components/schemas/EditableFields_description'
        customerPostalCode:
          $ref: '#/components/schemas/EditableFields_customerPostalCode'
        customerSegment:
          $ref: '#/components/schemas/EditableFields_customerSegment'
    FieldNotFound:
      type: object
      properties:
        message:
          type: string
          example: We didn't found information about that field.
    Error400:
      type: object
      properties:
        code:
          type: string
          example: "0015"
        status:
          type: string
          example: BAD_REQUEST
        message:
          type: string
          example: Bad Request
        detailMsg:
          type: string
    Error401:
      type: object
      properties:
        code:
          type: string
          example: "0003"
        status:
          type: string
          example: UNAUTHORIZED
        message:
          type: string
          example: Unauthorized
        detailMsg:
          type: string
    Error404:
      type: object
      properties:
        code:
          type: string
          example: "0004"
        status:
          type: string
          example: NOT_FOUND
        message:
          type: string
          example: Not found
        detailMsg:
          type: string
          example: Resource not found
    Error500:
      type: object
      properties:
        code:
          type: string
          example: "0002"
        status:
          type: string
          example: UNEXPECTED
        message:
          type: string
          example: Unexpected Error
        detailMsg:
          type: string
    TransitionsResponse:
      type: object
      properties:
        transitions:
          type: array
          example:
          - id: 41
            name: Reasignar
            status: Asignado
          - id: 21
            name: Resolver
            status: RESUELTO
          items:
            $ref: '#/components/schemas/TransitionsResponse_transitions'
    TicketTypesResponse:
      type: object
      properties:
        projects:
          type: array
          items:
            $ref: '#/components/schemas/TicketTypesResponse_projects'
    inline_response_201:
      type: object
      properties:
        id:
          type: string
          example: "123456789"
        key:
          type: string
          example: '##-1234'
    inline_response_201_1:
      type: object
      properties:
        message:
          type: string
          example: Attachment added successfully.
    inline_response_201_2:
      type: object
      properties:
        message:
          type: string
          example: Comment added successfully.
    inline_response_201_3:
      type: object
      properties:
        message:
          type: string
          example: Attachment with comment added successfully.
    TicketResponse_attachment:
      type: object
      properties:
        name:
          type: string
          example: attachment.txt
        data:
          type: string
          example: SGVsbG8gd29ybGQgZnJvbSBNUywgY2hhbmdlZA==
        mimeType:
          type: string
          example: multipart/form-data
    CreationDataInfo_subscriptionNumber:
      type: object
      properties:
        required:
          type: boolean
          example: true
        name:
          type: string
          example: Suscripción
    CreationDataInfo_icc:
      type: object
      properties:
        required:
          type: boolean
          example: false
        name:
          type: string
          example: ICC
    CreationDataInfo_contactEmail:
      type: object
      properties:
        required:
          type: boolean
          example: false
        name:
          type: string
          example: Email del Cliente
    EditableFields_description:
      type: object
      properties:
        name:
          type: string
          example: Descripción
        required:
          type: boolean
          example: true
    EditableFields_customerPostalCode:
      type: object
      properties:
        name:
          type: string
          example: Código Postal
        required:
          type: boolean
          example: false
    EditableFields_customerSegment_allowedValues:
      type: object
      properties:
        value:
          type: string
    EditableFields_customerSegment:
      type: object
      properties:
        name:
          type: string
          example: Segmento Cliente
        required:
          type: boolean
          example: false
        allowedValues:
          type: array
          example:
          - value: EMPRESA
          - value: RESIDENCIAL
          - value: HORECA
          - value: AUTONOMO
          items:
            $ref: '#/components/schemas/EditableFields_customerSegment_allowedValues'
    TransitionsResponse_transitions:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        status:
          type: string
    TicketTypesResponse_ticketTypes:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
    TicketTypesResponse_projects:
      type: object
      properties:
        key:
          type: string
        name:
          type: string
        ticketTypes:
          type: array
          items:
            $ref: '#/components/schemas/TicketTypesResponse_ticketTypes'
  responses:
    TicketResponse:
      description: Ticket response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TicketResponse'
    FieldResponse:
      description: Get field information
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FieldResponse'
    CreationDataInfo:
      description: Fields for ticket type
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreationDataInfo'
    EditableFields:
      description: Editable Fields for ticket
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EditableFields'
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error400'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error401'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error404'
    FieldNameNotFound:
      description: Field name not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FieldNotFound'
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error500'
    TransitionsResponse:
      description: Get transitions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TransitionsResponse'
    TicketTypes:
      description: Get ticket types
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TicketTypesResponse'
  parameters:
    xApiKey:
      name: x-api-key
      in: header
      required: true
      style: simple
      explode: false
      schema:
        type: string
    ticketId:
      name: ticketId
      in: path
      description: The Ticket ID in MasMovil ticketing tool. You can use either ID
        or KEY.
      required: true
      style: simple
      explode: false
      schema:
        type: string
    expand:
      name: expand
      in: query
      description: Filter for ticket response body. (You must add 'attachment' query
        param to get ticket attachments in response body)
      required: false
      style: form
      explode: true
      schema:
        type: array
        items:
          type: string
          enum:
          - attachment
    fieldName:
      name: fieldName
      in: path
      description: The field name in MasMovil ticketing API.
      required: true
      style: simple
      explode: false
      schema:
        type: string
        example: customerSegment
    projectKey:
      name: projectKey
      in: query
      description: The project key in MasMovil ticketing tool
      required: true
      style: form
      explode: true
      schema:
        type: array
        items:
          type: string
          enum:
          - MAS
    ticketType:
      name: ticketType
      in: query
      description: The ticket type in MasMovil ticketing tool
      required: true
      style: form
      explode: true
      schema:
        type: array
        items:
          type: string
          enum:
          - Avería (FTTH)
          - Avería Cliente
          - Incidencia
          - Reclamación Instalación
          - Cancelación Cliente
  examples:
    NetworkIncident:
      value:
        project: IDR
        summary: Ticket summary
        description: This is a ticket description example
        ticketType: Incidencia Red
        createdDate: 2019-08-20T10:29:29.908+1100
        massive: "NO"
        criticality: N1-Crítica o de corte
        unavailability: SI
        affectedNetworkElement: Network Element
        affectedNetworkType: Voz-Red Mercurio
        affectedBusiness: Empresas
        eventStartDate: 2019-08-19T10:29:29.908+1100
        title: test
    FTTHFault:
      value:
        project: MAS
        summary: Ticket summary
        description: This is a ticket description example
        ticketType: Avería (FTTH)
        createdDate: 2019-08-20T10:29:29.908+1100
        queue: SAC 1er Nivel
    UpdateStatus:
      value:
        transitionId: 11
    UpdatePriority:
      value:
        priority: High
    UpdateGroup:
      value:
        assignedGroup: NOC-HD-FIJO
    Attachment:
      value:
        name: image_example.jpg
        data: R0lGODdhAQABAPAAAP8AAAAAACwAAAAAAQABAAACAkQBADs
    Comment:
      value:
        body: This is a comment example
    SearchExample:
      value:
        filters:
          project: MAS
          customerDocument:
            $like: 50744198B
        startAt: 0
        maxResults: 10
        fields:
        - key
        - summary
        - issuetype
        - status
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
